// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGtetKXPMJLpq_iVYIVjwvW7ca56zfM98',
    appId: '1:397876596986:web:83d25d279c445a8c793943',
    messagingSenderId: '397876596986',
    projectId: 'graduationproject-16b5c',
    authDomain: 'graduationproject-16b5c.firebaseapp.com',
    storageBucket: 'graduationproject-16b5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9spx948mE2o2bIZluxwdsWP1QOhOyin8',
    appId: '1:397876596986:android:a7e76e82626e3723793943',
    messagingSenderId: '397876596986',
    projectId: 'graduationproject-16b5c',
    storageBucket: 'graduationproject-16b5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7f7VCzLmlsjqTWNbhU1PgvIgIcnAPfTE',
    appId: '1:397876596986:ios:77e8a31aa407fe37793943',
    messagingSenderId: '397876596986',
    projectId: 'graduationproject-16b5c',
    storageBucket: 'graduationproject-16b5c.appspot.com',
    iosClientId: '397876596986-giejum702slkfrf5k78pn4es4ncuuap4.apps.googleusercontent.com',
    iosBundleId: 'com.example.blood4life',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7f7VCzLmlsjqTWNbhU1PgvIgIcnAPfTE',
    appId: '1:397876596986:ios:77e8a31aa407fe37793943',
    messagingSenderId: '397876596986',
    projectId: 'graduationproject-16b5c',
    storageBucket: 'graduationproject-16b5c.appspot.com',
    iosClientId: '397876596986-giejum702slkfrf5k78pn4es4ncuuap4.apps.googleusercontent.com',
    iosBundleId: 'com.example.blood4life',
  );
}
